name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev

jobs:
  test-and-lint-backend:
    name: Test and Lint Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint --if-present

      # - name: Run backend tests # Assuming Jest is configured
      #   run: npm test

  # TODO: Add job for frontend tests and linting when frontend is set up
  # test-and-lint-frontend:
  #   name: Test and Lint Frontend
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./frontend
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18'
  #         cache: 'npm'
  #         cache-dependency-path: frontend/package-lock.json
  #     - name: Install frontend dependencies
  #       run: npm ci
  #     - name: Run linters
  #       run: npm run lint --if-present
  #     - name: Run frontend tests
  #       run: npm test
  #     - name: Build frontend
  #       run: npm run build --if-present
